services:
  database:
    image: postgres:15
    container_name: sistema_visitante_db_prod
    hostname: sistema-db-prod
    environment:
      POSTGRES_DB: neondb_prod
      POSTGRES_USER: neondb_owner_prod
      POSTGRES_PASSWORD: npg_prod_senha
    ports:
      - "5786:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
     # - ./backup_neondb.sql:/docker-entrypoint-initdb.d/backup_neondb.sql:ro
    networks:
      - app-network-prod
    restart: always

  backend:
    image: "${DOCKER_USERNAME}/liberae:${IMAGE_TAG}"
    container_name: sistema_visitante_backend_prod
    hostname: sistema-backend-prod
    ports:
      - "3707:3001"
    environment:
      - DB_CLIENT=pg
      - NODE_ENV=production_local
      - DATABASE_URL=postgresql://neondb_owner_prod:npg_prod_senha@database:5432/neondb_prod
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=neondb_owner_prod
      - DB_PASSWORD=npg_prod_senha
      - DB_NAME=neondb_prod
      - DB_DATABASE=neondb_prod
      - PGSSLMODE=disable
      - DB_SSL=false
      - SSL_REJECT_UNAUTHORIZED=false
      - PORT=3001
    working_dir: /app
    depends_on:
      - database
    restart: always
    networks:
      - app-network-prod
  nginx:
    image: nginx:alpine
    container_name: nginx_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    depends_on:
      - backend

volumes:
  postgres_data_prod:

networks:
  app-network-prod:
    driver: bridge

